## get genres https://api.themoviedb.org/3/genre/tv/list?api_key=d3db47f451e0a89699b83c9dd2944439&language=en-US

## GET https://api.themoviedb.org/3/trending/movie/week?api_key=d3db47f451e0a89699b83c9dd2944439

##https://api.themoviedb.org/3/search/movie?api_key=d3db47f451e0a89699b83c9dd2944439&language=en-US&query=movienmae&page=1&include_adult=false

##GET https://api.themoviedb.org/3/find/610253?api_key=d3db47f451e0a89699b83c9dd2944439&language=en-US&external_source=imdb_id


##Create a new REQUEST TOKEN  
##Get the user to authorize the request token
##Create a new SESSION ID with the athorized request token


## 1 Create a new REQUEST TOKEN  : 
## get request
##GET https://api.themoviedb.org/3/authentication/token/new?api_key=d3db47f451e0a89699b83c9dd2944439

## redirect so the user can choose to accept or deny 
## 2 Get the user to authorize the REQUEST TOKEN : 
##GET https://www.themoviedb.org/authenticate/{REQUEST_TOKEN}?redirect_to=http://localhost:3000/approved


## 3 Create a new SESSION ID with the athorized request token : 

##24af9dba71bf945cb604d59893d1f63898815f7a
##1b4e2b249c835b8ee87960b4aa8ae441ac06261d
POST https://api.themoviedb.org/3/authentication/session/new?api_key=d3db47f451e0a89699b83c9dd2944439 

{
  "request_token": "6bc047b88f669d1fb86574f06381005d93d3517a"
}

##{"success":true,"session_id":"a12e1a615f57d681f09bd675187528b7a50949a5"}